### ISSUE TITLE
Travis: Deploying to S3 does not work following maven-semantic-release

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-server#165]
The deploy to s3 stage of our travis script fails on a merge to master (release)

see https://travis-ci.org/conveyal/datatools-server/builds/476454218#L2079:

```
The command "cp "target/dt-$(git describe --always).jar" "deploy/dt-latest-${BRANCH}.jar"" failed and exited with 1 during .
```

My guess here is that the `target/` directory and its jar files are not present after maven-semantic-release runs.

**Comment by evansiroky** [comment]
@landonreed was this fixed with https://github.com/conveyal/datatools-server/pull/160?

**Comment by landonreed** [comment]
Yes, I believe so.
