### ISSUE TITLE
No API route configured for this path

### ISSUE THREAD

**Issue by karimhm** [ibi-group/datatools-server#202]
## Observed behavior
When i try to import a feed or create a new one i get the following error: **No API route configured for this path.**

I get this log:

`May 30 20:59:41.903 [qtp221294552-29] INFO  c.c.d.common.utils.SparkUtils:224 - res (200) REDECATED@REDECATED.com GET: http://localhost:9966/api/manager/secure/feedsource/02edfc82-4b45-42d0-b18c-c5e1a48e33b6
{
  "id" : "02edfc82-4b45-42d0-b18c-c5e1a48e33b6",
  "dateCreated" : 1559246091998,
  "projectId" : "dc4b0b6d-b100-4cca-9ed7-f7eadcdcd0b7",
  "name" : "NAME",
  "isPublic" : false,
  "deployable" : false,
  "retrievalMethod" : "MANUALLY_UPLOADED", 
...and 13 more lines
May 30 20:59:41.987 [qtp221294552-29] INFO  c.c.d.common.utils.SparkUtils:224 - req REDECATED@REDECATED.com GET: http://localhost:9966/api/manager/secure/feedversion?feedSourceId=02edfc82-4b45-42d0-b18c-c5e1a48e33b6
null
May 30 20:59:42.120 [qtp221294552-27] INFO  c.c.d.common.utils.SparkUtils:224 - req REDECATED@REDECATED.com GET: http://localhost:9966/api/editor/secure/snapshot?feedId=02edfc82-4b45-42d0-b18c-c5e1a48e33b6
null
May 30 20:59:42.121 [qtp221294552-27] INFO  c.c.d.common.utils.SparkUtils:115 - Halting with status code 404.  Error message: No API route configured for this path..
May 30 20:59:42.121 [qtp221294552-27] INFO  c.c.d.common.utils.SparkUtils:224 - res (404) REDECATED@REDECATED.com GET: http://localhost:9966/api/editor/secure/snapshot?feedId=02edfc82-4b45-42d0-b18c-c5e1a48e33b6
{
  "result" : "ERR",
  "message" : "No API route configured for this path.",
  "code" : 404,
  "detail" : null
}`

## Version of datatools-server and datatools-ui
datatools-server: 6b36529d953d2eab2c55b75776878453b1a452ef
datatools-ui: [b75e7d2](https://github.com/ibi-group/datatools-ui/commit/b75e7d2669d060b016a77b191bc15fc80d7fa489)

**Comment by landonreed** [comment]
This is likely an issue with your configuration files. Perhaps the editor module is not enabled.
