### ISSUE TITLE
FeedVersions can be generated with duplicate IDs

### ISSUE THREAD

**Issue by evansiroky** [ibi-group/datatools-server#251]
## Observed behavior

The method that generates a FeedVersionID is not guaranteed to generate unique ids as it uses an ID with data up to the second. So if two or more feed versions from the same source are generated at the same second, duplicate IDs will be generated.

https://github.com/ibi-group/datatools-server/blob/f5a80c6efa57bc9ad6166af3b5256392a9b280cd/src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java#L65-L72

## Expected behavior

FeedVersions should always be created with unique IDs.

## Steps to reproduce the problem

See failing test case in #252.

## Any special notes on configuration used

N/A

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

f5a80c6efa57bc9ad6166af3b5256392a9b280cd

**Comment by landonreed** [comment]
True. One approach to fix this would be to limit the creation of only one feed version at a time for each feed source. The other, of course, would be to change the feed version ID generation to be a UUID.

**Comment by landonreed** [comment]
Oh, interesting. I'm seeing now in https://github.com/ibi-group/datatools-server/pull/253 that these feed versions were created one after the other (synchronously), but I suppose the first one was so small that it finished within the second.
