### ISSUE TITLE
Mapping frontend to backend without URL

### ISSUE THREAD

**Issue by dudebrains01** [ibi-group/datatools-server#283]
Hey folks!
I'm trying to run the GTFS editor without AWS and have a small issue,
My backend runs very well but I am not sure how to link datatools-server to datatools-ui with the URL as my frontend files are stored locally (on my machine).
**What should I put in for the server.yml client_asset_url?**

FYI I'm running windows 10

Thanks ahead of time.

**Comment by landonreed** [comment]
If running the software locally, I would recommend following the instructions set forth in the [Front End section](https://data-tools-docs.ibi-transit.com/en/dev/dev/development/#front-end) of the Development docs. You could also configure a web server for a single page app and return the `index.html` for any request (but proxy `/api` calls to the back end).
