### ISSUE TITLE
Network error (500) on /api/manager/secure/status/jobs request

### ISSUE THREAD

**Issue by vandeag** [ibi-group/datatools-server#284]
## Observed behavior

After setting up a fresh copy from dev branch latest commit of datatools-server and UI,  I'm getting a Network Error for the Job status request all the time with 500 internal server error response. 

<img width="1019" alt="networkerror1" src="https://user-images.githubusercontent.com/9696889/75881072-bb24c380-5e1e-11ea-9473-71daa304ae0a.png">

<img width="679" alt="networkerror2" src="https://user-images.githubusercontent.com/9696889/75881296-0d65e480-5e1f-11ea-92f4-8d9464f3e4c2.png">

In the earlier version of datatools it worked fine. Any suggestions? 

## Expected behavior

No network error.

## Steps to reproduce the problem

Goto Login page. After logging in the error comes up.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

Branch: dev
Commit: latest
 
with UI
UI Version: | dcfcf1
-- | --
UI deployed at: | March 4, 2020 1:24 PM

**Comment by landonreed** [comment]
Hi, this is likely an issue with your configuration (perhaps Auth0).
