### ISSUE TITLE
Java throwing exception - databaseName can not be null

### ISSUE THREAD

**Issue by dudebrains01** [ibi-group/datatools-server#311]
## Observed behavior
Upon trying to deploy the backend, Java throws an exception when running dt-v3.2.0-773-g495f7c7.jar

See screenshots for details
![image](https://user-images.githubusercontent.com/46612183/81315861-d8f9e900-9058-11ea-9420-64dc6e9860b2.png)
![image](https://user-images.githubusercontent.com/46612183/81315897-e7e09b80-9058-11ea-9eb3-25fc07ba6e3a.png)

## Expected behavior

Backend deploying

## Steps to reproduce the problem

java -jar target/dt-v3.2.0-773-g495f7c7.jar configurations/default/env.yml configurations/default/server.yml

Please describe any applicable config files that were used
standard env.yml and server.yml
Only modifications are for api keys...

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)
af00ed

@landonreed would you happen to have a solution to this issue?

**Comment by landonreed** [comment]
Apologies for the delayed response, it looks either MongoDB is not running or the `MONGO_DB_NAME` in `env.yml` has not been set.
