### ISSUE TITLE
Modify existing user metadata if Auth0 user already exists when creating user

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-server#337]
## Observed behavior

When an Auth0 user already exists in the tenant when creating a new user in data tools, an error is encountered.

## Expected behavior

Instead of failing to create the new user, the existing Auth0 user's metadata should be modified to include the permissions for the new data tools user account.

## Steps to reproduce the problem

1. Create user through Auth0 portal for email account (with no user metadata).
2. Open data tools user admin, and attempt to create user for same email.
3. See error.

## Any special notes on configuration used

N/A

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

latest dev

**Comment by binh-dam-ibigroup** [comment]
Closing. This was fixed by #338.
