### ISSUE TITLE
Mongo should initialize automatically but datatools-server crashes with lack of user/pass when trying to connect to MongoDB

### ISSUE THREAD

**Issue by wkulesza** [ibi-group/datatools-server#370]
Hi,
according to docs, there's no need to setup mongo, as it should initialize automatically:
```There is no need to manually initialize a database in MongoDB (MongoDB will handle this automatically if you prefer)```

Was there a change recently perhaps, where Mongo would force some kind of authorisation upon starting up data tools ?
When we're trying to run it, datatools-server crashes informing that it could not find mongo_user and mongo_password config properties, as well as bugsnag_key ?

As a result, when it tries to connect to mongodb instance at mongodb://localhost:27017/catalogue it fails with Exception in monitor thread while connecting to server localhost:21017, Exception opening socket and connection refused.

Thanks for any pointers.

**Comment by landonreed** [comment]
Hi @wkulesza, are there server logs you could paste in here showing the crash?

**Comment by wkulesza** [comment]
I was able to  catch those errors:
[http://prntscr.com/10q9938](url)
[http://prntscr.com/10q99fz](url)

**Comment by landonreed** [comment]
So those items in the first screenshot are not errors (just warnings) and should not be the source of any issues with Mongo. It looks like perhaps your local MongoDB instance is just not running. I might try running `mongo` in a terminal window or check the process with something like `lsof -i:27017`.

**Comment by wkulesza** [comment]
@landonreed mongo is running but the problem is that datatools-server forces the "localhost" instead of for example 127.0.0.1 url of the mongodb. Where can we change this ?

**Comment by landonreed** [comment]
You should be able to change this with the `MONGO_URI` property in your `env.yml` file. E.g.:

https://github.com/ibi-group/datatools-server/blob/47371e0578cc7ad2cac876c882df665e5c7088d0/configurations/default/env.yml.tmp#L18-L19

**Comment by wkulesza** [comment]
Yes, whatever i set in this file is omitted and error log of server shows that it tries to connect to localhost:27017.

I'm checking if this is the responsible fragment of code and changing this from localhost:27017 to 127.0.0.1:27017

https://github.com/ibi-group/datatools-server/blob/47371e0578cc7ad2cac876c882df665e5c7088d0/src/main/java/com/conveyal/datatools/manager/persistence/Persistence.java#L37

**Comment by landonreed** [comment]
Ah, yes, it looks like that default config value is out-of-date. You should definitely use `MONGO_HOST` instead. Does that seem to work for you?

**Comment by wkulesza** [comment]
Tried to replace MONGO_URI with MONGO_HOST

in env.yml i have now:
MONGO_HOST: mongodb://127.0.0.1:27017 (tried also with localhost and datatools-mongodb - as that is my container id when im trying to run it in dockers)

and this is the error im getting from datatools-server now (after doing java -jar target/dt-v3.2.0-1048-g47371e0.jar  /opt/datatools-server/configurations/default/env.yml /opt/datatools-server/configurations/default/server.yml:

```
WARN  2021-04-16T14:46:38.947 [main] c.c.datatools.manager.DataManager(DataManager.java:415) Config property BUGSNAG_KEY not found
WARN  2021-04-16T14:46:39.222 [main] c.c.datatools.manager.DataManager(DataManager.java:415) Config property MONGO_USER not found
WARN  2021-04-16T14:46:39.223 [main] c.c.datatools.manager.DataManager(DataManager.java:415) Config property MONGO_PASSWORD not found
Exception in thread "main" java.lang.IllegalArgumentException: The connection string contains an invalid host 'mongodb:'. The port '' is not a valid, it must be an integer between 0 and 65535
        at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1003)
        at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:983)
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:340)
        at com.conveyal.datatools.manager.persistence.Persistence.initialize(Persistence.java:93)
        at com.conveyal.datatools.manager.DataManager.initializeApplication(DataManager.java:155)
        at com.conveyal.datatools.manager.DataManager.main(DataManager.java:122)
```

**Comment by landonreed** [comment]
`mongodb` is the protocol for the connection and should not be included in `MONGO_HOST`.

**Comment by wkulesza** [comment]
it helped. thanks a lot!
