### ISSUE TITLE
Older GTFS Feeds Can Not Be Updated

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [ibi-group/datatools-server#420]
## Observed behavior

Older GTFS feeds fail to have stops updated, because the database fields required are missing, even after migration.

## Expected behavior

The stop should update as usual.

## Steps to reproduce the problem

Open a feed. Open a stop. Edit any field of that stop. Some feeds will save as expected, some will fail with a message similar to 
```
org.postgresql.util.PSQLException: ERROR: column "platform_code" is of type smallint but expression is of type character varying
Hint: You will need to rewrite or cast the expression.
Position: 273
```

Another observed error (upon attempting to adjust pattern)
```
org.postgresql.util.PSQLException: ERROR: column "continuous_pickup" of relation "stop_times" does not exist
Position: 108
```

## Any special notes on configuration used

n/a

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

latest dev

**Comment by binh-dam-ibigroup** [comment]
Fixed by https://github.com/ibi-group/configurations/pull/190.
