### ISSUE TITLE
Unable to login after newest update of datatools-server

### ISSUE THREAD

**Issue by wkulesza** [ibi-group/datatools-server#487]
## Observed behavior

After using the newest dev branch and dt-v3.2.0-1644-g2a725e9.jar server, auth0 user is not allowed to login to datatools.

## Expected behavior

After providing auth0 credentials, user should be allowed to login

## Steps to reproduce the problem

Run dt-v3.2.0-1644-g2a725e9.jar server, configure auth0 with appropriate client id, auth0 application and token along with certificate file (pem) and open up datatools in browser. you will end up with an error "Cannot fetch without user token." and "Error: Unauthorized".
Also, with previous dev branch version, login screen was different and now it's more auth0 style.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

Newest dev of datatools-ui and datatools-server

**Comment by miles-grant-ibigroup** [comment]
Hi @wkulesza thanks for reporting this. In hindsight we should've made this change a breaking change! For now, here are the steps to adjust the configuration to get login to work again.

First, change your auth0 signing algorithm from HS256 to RS256. 

Next, adjust your server `env.yml` to REMOVE your `AUTH0_SECRET` and instead use `AUTH0_PUBLIC_KEY` (see https://github.com/ibi-group/datatools-server/blob/dev/configurations/default/env.yml.tmp#L4 for details).

On the client, you'll have to add `AUTH0_CONNECTION_NAME` (see https://github.com/ibi-group/datatools-ui/blob/dev/configurations/default/env.yml.tmp#L2)

I hope this is helpful and please let me know if these steps work for you!

**Comment by wkulesza** [comment]
@miles-grant-ibigroup thanks for pointers.
auth0 - already used RS256
env.yml in server - already used AUTH0_PUBLIC_KEY (linking to a generated auth.pem file) and using AUTH0_TOKEN - generated within auth0.com

env.yml in ui - trying to locate it in auth0 following this: [https://auth0.com/docs/authenticate/identity-providers/locate-the-connection-id](url). Is it the Identifier just below the name of Database connection? BTW, my setting for "Requires Username" is disabled.

**Comment by miles-grant-ibigroup** [comment]
@binh-dam-ibigroup may be able to advise better than I can

**Comment by wkulesza** [comment]
@miles-grant-ibigroup @binh-dam-ibigroup guys, if this helps,
i'm getting this in console:
```
ncaught Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
```

**Comment by miles-grant-ibigroup** [comment]
Oh we ran into a similar issue when running datatools via docker. Auth0 refused to log in unless the page is served from `localhost` or an https website.

We solved it like this: https://github.com/ibi-group/datatools-ui/tree/dev/__tests__/e2e/ui-proxy

**Comment by wkulesza** [comment]
I'm trying to run this with https, but using proxypass from apache, so that i can use subdomain - but this ends up with unable to login.

**Comment by miles-grant-ibigroup** [comment]
Make sure the domain you're running on is whitelisted in the auth0 settings!

**Comment by wkulesza** [comment]
It is. You mean in Allowed Callback URL, logout urls, web origins, CORS in the auth0 app settings ?

**Comment by miles-grant-ibigroup** [comment]
If the issue you're seeing is that chrome is saying that the origin is not secure then you may need to include `--ignore-certificate-errors` flag when launching chrome. There might be other chrome changes you need to change as well to get it to accept your domain as a secure origin

**Comment by binh-dam-ibigroup** [comment]
> env.yml in ui - trying to locate it in auth0 following this: [https://auth0.com/docs/authenticate/identity-providers/locate-the-connection-id](url). Is it the Identifier just below the name of Database connection? BTW, my setting for "Requires Username" is disabled.

@wkulesza The value for `AUTH0_CONNECTION_NAME` is the name of one of the connections listed under one of the authentication methods in the "Authentication" section in the Auth0 Dashboard. In the screenshot case below, it would be string starting with "Username-P..." You might not need this parameter, as it is used mainly to send a password reset email to users.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/56846598/193825594-881e11f4-9c7f-4173-81bb-c8a5de94e061.png">

**Comment by wkulesza** [comment]
> If the issue you're seeing is that chrome is saying that the origin is not secure then you may need to include `--ignore-certificate-errors` flag when launching chrome. There might be other chrome changes you need to change as well to get it to accept your domain as a secure origin

Thanks for further pointers. What is interesting to see, is that this setup was working for me (ui 8c7e1 and server 1ba68d) and only yesterday, i tried building it from scratch again using newest devs. When the DataTools page loaded white-blank, I tried setting up https on that machine (using letsecnrypt i was able to add https) but got stuck afterwards.

**Comment by wkulesza** [comment]
If this helps, when i try to run with http, i get white page, and if i try to use subdomain of apache and use proxypass to pass to localhost:8888 (this is the port for nginx i have setup), im getting this:
![obraz](https://user-images.githubusercontent.com/1014296/193874874-fa20a53f-cbf7-4f00-9ab3-2c56fc1bc1a6.png)

**Comment by binh-dam-ibigroup** [comment]
I would check that the domain is whitelisted in Auth0(Allowed Callback URL, logout urls, web origins, CORS). The only other place I can think of is Grant Types (under Advanced Settings for your auth0 client app), where we use:
- Implicit
- Authorization Code
- Refresh Token

**Comment by wkulesza** [comment]
All is correct, and i haven't changed this - the only thing that was changed is that i used dev branch again to rebuild.
Also, im using npm i -g serve and mastarm --env dev (instead of production) for datatools-ui as instructed earlier by miles.

**Comment by miles-grant-ibigroup** [comment]
> If this helps, when i try to run with http, i get white page, and if i try to use subdomain of apache and use proxypass to pass to localhost:8888 (this is the port for nginx i have setup), im getting this:
> ![obraz](https://user-images.githubusercontent.com/1014296/193874874-fa20a53f-cbf7-4f00-9ab3-2c56fc1bc1a6.png)

The 401 you're getting from auth0 makes me think it's a permissions issue with your auth0 config. Auth0 is rejecting the token, likely because of an incorrect origin! I wish there were a clearer solution :(

**Comment by binh-dam-ibigroup** [comment]
Could you try to log out (or delete datatools Auth0 cookies from your browser) and log back in? Auth0 tokens from the two encoding methods are not interchangeable.

**Comment by wkulesza** [comment]
Tried. no luck.
Digging in deeper and when i tried to generate auth0 token to insert it into env.yml, i got this when following https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens:

```
{"error":"unauthorized_client","error_description":"Grant type 'client_credentials' not allowed for the client.","error_uri":"https://auth0.com/docs/clients/client-grant-types"}
```
Obviously i'm providing correct client_id, client_secret and your api identifier...

**Comment by miles-grant-ibigroup** [comment]
> Tried. no luck. Digging in deeper and when i tried to generate auth0 token to insert it into env.yml, i got this when following https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens:
> 
> ```
> {"error":"unauthorized_client","error_description":"Grant type 'client_credentials' not allowed for the client.","error_uri":"https://auth0.com/docs/clients/client-grant-types"}
> ```
> 
> Obviously i'm providing correct client_id, client_secret and your api identifier...

You should be able to enable `client_credentials` grant type in auth0 settings.

**Comment by wkulesza** [comment]
Yes, disabled this before, now enabled again and generated token. Will try to rebuild once more and come back with result.

edit: Unfortunately, no change...I get the very same error:

Error: Unauthorized
and
Cannot fetch without user token.
Tried both mastarm -env test and production

**Comment by wkulesza** [comment]
I sorted it out - the only thing i needed to change was in auth0:

Changed Token Endpoint Authentication Method from Basic to None and confirm the popup modal message.

**Comment by miles-grant-ibigroup** [comment]
Happy to hear you got it fixed! Thanks for sharing as well. Hopefully this thread will be useful to others in the future.
